# ==========================================
# 4. Frontend UI Deployment & Service (React + Nginx)
# ==========================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-frontend
  labels:
    app: task-management
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-management
      tier: frontend
  template:
    metadata:
      labels:
        app: task-management
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: prajwal3466/task-frontend:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: task-management
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 30080
      name: http
  selector:
    app: task-management
    tier: frontend
